package modelo.enums;

public enum Tipo{
	REMERACORTA, REMERALARGA, BUZO, SWEATER, CAMPERA, CAMISA, SACO,
	SHORTS, JOGGINGS, JEANS, BERMUDAS, PANTALON,
	ZAPATILLAS, ZAPATOS, ZAPATOSDETACON, OJOTAS,
	BUFANDA, ANTEOJOS, GORRA, COLLAR, LENTES, AROS,
	VESTIDO, SMOKING, TRAJE;
}
