package modelo;

public class ClasesUtilsPrendas {
	
public enum Tela{
		TWEED, GABARDINA, LINO, FRANELA, CREPE, ENCAJE, OXFORD, CUERO, JEAN, SEDA, LYCRA, POLAR,
		TERCIOPELO, ALGODON
	}
	
public enum Color{
		BLANCO, NEGRO, AZUL, ROJO, VERDE, AMARILLO, VIOLETA, ROSA, SALMON, MARRON, GRIS, NARANJA, 
		CELESTE, BORDO, BEIGE, CAQUI, CARMESI, TURQUESA, NULL
	}

}
